
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class KayitOlSayfasi extends javax.swing.JFrame {


    Islemler yeniIslem=new Islemler();
    private static String removeLastChar(String str) {
    return str.substring(0, str.length() - 2);
      
}
    private static int i;
    private static int [] dizi= new int[3];
    private static String email2;

    public static String getEmail2() {
        return email2;
    }
    


    public static int[] getDizi() {
        return dizi;
    }

    public static void setDizi(int[] dizi) {
        KayitOlSayfasi.dizi = dizi;
    }
     
    /**
     * Creates new form GirisSayfasi
     */
    public KayitOlSayfasi() {
        getContentPane().setBackground(Color.BLACK);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kullanicim = new javax.swing.JTextField();
        parola = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        yıl = new javax.swing.JTextField();
        isim = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AksiyonMacera = new javax.swing.JCheckBox();
        Korku = new javax.swing.JCheckBox();
        Romantik = new javax.swing.JCheckBox();
        Drama = new javax.swing.JCheckBox();
        Reality = new javax.swing.JCheckBox();
        CocukveAile = new javax.swing.JCheckBox();
        Belgesel = new javax.swing.JCheckBox();
        Gerilim = new javax.swing.JCheckBox();
        Anime = new javax.swing.JCheckBox();
        BilimDoga = new javax.swing.JCheckBox();
        BilimFantastik = new javax.swing.JCheckBox();
        Aksiyon = new javax.swing.JCheckBox();
        Komedi = new javax.swing.JCheckBox();
        BilimKurgu = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        baslangicemail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        yeniparolam = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giriş-Kayıt");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 600));
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("e-mail: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(72, 130, 60, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sifre: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(72, 171, 70, 16);
        getContentPane().add(kullanicim);
        kullanicim.setBounds(175, 117, 283, 30);
        getContentPane().add(parola);
        parola.setBounds(175, 158, 283, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton2.setText("Kayıt ol");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 470, 110, 37);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Doğum Yılı:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(72, 84, 70, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ad-Soyad:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(72, 36, 80, 20);
        getContentPane().add(yıl);
        yıl.setBounds(175, 71, 283, 30);
        getContentPane().add(isim);
        isim.setBounds(175, 29, 283, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tür:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(72, 220, 50, 16);

        AksiyonMacera.setForeground(new java.awt.Color(255, 255, 255));
        AksiyonMacera.setText("Aksiyon ve Macera");
        getContentPane().add(AksiyonMacera);
        AksiyonMacera.setBounds(147, 368, 160, 23);

        Korku.setForeground(new java.awt.Color(255, 255, 255));
        Korku.setText("Korku");
        getContentPane().add(Korku);
        Korku.setBounds(350, 368, 140, 23);

        Romantik.setForeground(new java.awt.Color(255, 255, 255));
        Romantik.setText("Romantik");
        getContentPane().add(Romantik);
        Romantik.setBounds(350, 270, 140, 23);

        Drama.setForeground(new java.awt.Color(255, 255, 255));
        Drama.setText("Drama");
        getContentPane().add(Drama);
        Drama.setBounds(147, 293, 160, 23);

        Reality.setForeground(new java.awt.Color(255, 255, 255));
        Reality.setText("Reality Program");
        getContentPane().add(Reality);
        Reality.setBounds(147, 394, 180, 23);

        CocukveAile.setForeground(new java.awt.Color(255, 255, 255));
        CocukveAile.setText("Çocuk ve Aile");
        getContentPane().add(CocukveAile);
        CocukveAile.setBounds(350, 394, 140, 23);

        Belgesel.setForeground(new java.awt.Color(255, 255, 255));
        Belgesel.setText("Belgesel");
        getContentPane().add(Belgesel);
        Belgesel.setBounds(350, 319, 180, 23);

        Gerilim.setForeground(new java.awt.Color(255, 255, 255));
        Gerilim.setText("Gerilim");
        getContentPane().add(Gerilim);
        Gerilim.setBounds(147, 319, 140, 23);

        Anime.setForeground(new java.awt.Color(255, 255, 255));
        Anime.setText("Anime");
        Anime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimeActionPerformed(evt);
            }
        });
        getContentPane().add(Anime);
        Anime.setBounds(147, 243, 100, 23);

        BilimDoga.setForeground(new java.awt.Color(255, 255, 255));
        BilimDoga.setText("Bilim ve Doğa");
        getContentPane().add(BilimDoga);
        BilimDoga.setBounds(350, 243, 150, 23);

        BilimFantastik.setForeground(new java.awt.Color(255, 255, 255));
        BilimFantastik.setText("Bilim Kurgu ve Fantastik Yapılar");
        getContentPane().add(BilimFantastik);
        BilimFantastik.setBounds(147, 270, 190, 23);

        Aksiyon.setForeground(new java.awt.Color(255, 255, 255));
        Aksiyon.setText("Aksiyon");
        getContentPane().add(Aksiyon);
        Aksiyon.setBounds(350, 293, 180, 23);

        Komedi.setForeground(new java.awt.Color(255, 255, 255));
        Komedi.setText("Komedi");
        getContentPane().add(Komedi);
        Komedi.setBounds(147, 345, 79, 23);

        BilimKurgu.setForeground(new java.awt.Color(255, 255, 255));
        BilimKurgu.setText("Bilim Kurgu");
        getContentPane().add(BilimKurgu);
        BilimKurgu.setBounds(350, 345, 180, 23);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sevdiğiniz film/dizi türlerinden 3 tanesini seçiniz: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(147, 220, 330, 16);

        jLabel7.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("E-mail  ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(806, 187, 70, 30);

        jLabel8.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sifre");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(818, 246, 42, 22);

        baslangicemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baslangicemailActionPerformed(evt);
            }
        });
        getContentPane().add(baslangicemail);
        baslangicemail.setBounds(888, 181, 170, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("GirisYap");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(870, 320, 115, 29);
        getContentPane().add(yeniparolam);
        yeniparolam.setBounds(890, 230, 170, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String email= kullanicim.getText();
        String parolam=new String(parola.getPassword());
        String isim1 = isim.getText();
        int  Dyil = Integer.parseInt(yıl.getText());
        String türler="";
        yeniIslem.varMı(email);
        boolean varMı = yeniIslem.varMı(email);
        
        int i=0;
                
         if(varMı){
           // mesaj.setText("Böyle bir kayıt zaten var.. " );
            
        }
        
        else{
           
            if(BilimFantastik.isSelected() ){
                türler+=BilimFantastik.getText()+", ";
                System.out.println(türler);
                dizi[i]=3;
                i++;
                yeniIslem.oneriyiGetir3();
            }
            if(Anime.isSelected()){
                türler+=Anime.getText()+", ";
                System.out.println(türler);
                dizi[i]=13;
                i++;
                yeniIslem.oneriyiGetir13();
            }
            if(Drama.isSelected()){
              türler+=Drama.getText()+", ";
                System.out.println(türler);
                dizi[i]=7;
                i++;
                yeniIslem.oneriyiGetir7();
            }
            if(Gerilim.isSelected()){
               türler+=Gerilim.getText()+", ";
                System.out.println(türler);
                dizi[i]=11;
                i++;
                yeniIslem.oneriyiGetir11();
            }
            if(Komedi.isSelected()){
                 türler+=Komedi.getText()+", ";
                System.out.println(türler);
                dizi[i]=8;
                i++;
                yeniIslem.oneriyiGetir8();
            }
            if(AksiyonMacera.isSelected()){
                türler+=AksiyonMacera.getText()+", ";
                System.out.println(türler);
                dizi[i]=6;
                i++;
                yeniIslem.oneriyiGetir6();
            }
            if(Reality.isSelected()){
                 türler+=Reality.getText()+", ";
                System.out.println(türler);
                dizi[i]=14;
                i++;
                yeniIslem.oneriyiGetir14();
            }
            if(BilimDoga.isSelected()){
                türler+=BilimDoga.getText()+", ";
                System.out.println(türler);
                dizi[i]=10;
                i++;
                yeniIslem.oneriyiGetir10();
            }
            if(Romantik.isSelected()){
                türler+=Romantik.getText()+", ";
                System.out.println(türler);
                dizi[i]=9;
                i++;
                yeniIslem.oneriyiGetir9();
                
            }
            if(Aksiyon.isSelected()){
                türler+=Aksiyon.getText()+", ";
                System.out.println(türler);
                dizi[i]=1;
                i++;
                yeniIslem.oneriyiGetir();
            }
            if(Belgesel.isSelected()){
                türler+=Belgesel.getText()+", ";
                System.out.println(türler);
                dizi[i]=4;
                i++;
                yeniIslem.oneriyiGetir4();
            }
            if(BilimKurgu.isSelected() ){
                türler+=BilimKurgu.getText()+", ";
                System.out.println(türler);
                dizi[i]=2;
                i++;
                yeniIslem.oneriyiGetir2();
            }
            if(Korku.isSelected() ){
                türler+=Korku.getText()+", ";
                System.out.println(türler);
                dizi[i]=12;
                i++;
                yeniIslem.oneriyiGetir12();
                
            }
            if(CocukveAile.isSelected() ){
                türler+=CocukveAile.getText()+", ";
                System.out.println(türler);
                dizi[i]=5;
                i++;
                yeniIslem.oneriyiGetir5();
                
            }
             
            
      
             yeniIslem.kayitOlustur(isim1, email, parolam, Dyil, removeLastChar(türler));
      
         
           JOptionPane.showMessageDialog(null, "Başarıyla kayıt alındı.....");
           
            
        
        }
         
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimeActionPerformed
            
          
    }//GEN-LAST:event_AnimeActionPerformed

    private void baslangicemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baslangicemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baslangicemailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        email2= baslangicemail.getText();
        String parolam=new String(yeniparolam.getPassword());
        //String isim1 = isim.getText();
        //int  Dyil = Integer.parseInt(yıl.getText());
        
        boolean varmı = yeniIslem.varMı(email2);
        if(varmı){
        Islemler.setMail(email2);
        NewJDialog1 Jdiolog= new NewJDialog1(this, true);
        setVisible(false);
        Jdiolog.setVisible(true);
        }
        else{

            JOptionPane.showMessageDialog(null, "Kayıtlı değilsiniz.Kayıt ol butonuna tıklayın!");

        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
 
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
        } catch (InstantiationException ex) {
        } catch (IllegalAccessException ex) {
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KayitOlSayfasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Aksiyon;
    private javax.swing.JCheckBox AksiyonMacera;
    private javax.swing.JCheckBox Anime;
    private javax.swing.JCheckBox Belgesel;
    private javax.swing.JCheckBox BilimDoga;
    private javax.swing.JCheckBox BilimFantastik;
    private javax.swing.JCheckBox BilimKurgu;
    private javax.swing.JCheckBox CocukveAile;
    private javax.swing.JCheckBox Drama;
    private javax.swing.JCheckBox Gerilim;
    private javax.swing.JCheckBox Komedi;
    private javax.swing.JCheckBox Korku;
    private javax.swing.JCheckBox Reality;
    private javax.swing.JCheckBox Romantik;
    private javax.swing.JTextField baslangicemail;
    private javax.swing.JTextField isim;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField kullanicim;
    private javax.swing.JPasswordField parola;
    private javax.swing.JPasswordField yeniparolam;
    private javax.swing.JTextField yıl;
    // End of variables declaration//GEN-END:variables
}
