
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class NewJDialog1 extends javax.swing.JDialog {
    DefaultTableModel model ; 
    DefaultTableModel model2;
    Islemler islem2= new Islemler();
    String email;
    private static Date tarihSaat;
    private static SimpleDateFormat bicim2;
    private static Date tarihSaat2;
    private static SimpleDateFormat bicim3;
    private static long beginTime = 0, endTime = 0,endTime2=0, beginTime2=0;
    private static String puan;
    private static String Ad;
    String [] dizi4= new String[6];
    private static String Tip;
    int [] dizim;
    
    JComboBox box2;
    private JLabel label;
 
   
    /**
     * Creates new form NewJDialog1
     */
    public NewJDialog1(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        initComponents();
        model=(DefaultTableModel)tablo.getModel();
        model2=(DefaultTableModel)tablo2.getModel();
        dizi4=Islemler.getDizi3();
    
      
        
        for(int j=0; j<6;j++){
            if(j==0){
            Film1.setText(dizi4[j]);
            }
            if(j==1){
            Film2.setText(dizi4[j]);
            }
            if(j==2){
            Film3.setText(dizi4[j]);
            }
            if(j==3){
            Film4.setText(dizi4[j]);
            }
            if(j==4){
            Film5.setText(dizi4[j]);
            }
            if(j==5){
            Film6.setText(dizi4[j]);
            }
            
        }
       
        Filmleri_goruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Film1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablo = new javax.swing.JTable();
        Film3 = new javax.swing.JLabel();
        Film5 = new javax.swing.JLabel();
        Film4 = new javax.swing.JLabel();
        Film6 = new javax.swing.JLabel();
        Film2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        arama = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablo2 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        arama2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton21 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        //jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(1300, 768));

        jPanel1.setBackground(new java.awt.Color(0,0,0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 2500));
        jPanel1.setLayout(null);

        Film1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Film1);
        Film1.setBounds(330, 70, 275, 36);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SIZIN ICIN SECTIKLERIMIZZ....");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(430, 20, 390, 57);

        tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProgramAdı", "ProgramTipi", "KacBolum", "ProgramUzunluk"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabloMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablo);
        if (tablo.getColumnModel().getColumnCount() > 0) {
            tablo.getColumnModel().getColumn(0).setResizable(false);
            tablo.getColumnModel().getColumn(1).setResizable(false);
            tablo.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(462, 360, 450, 234);

        Film3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Film3);
        Film3.setBounds(330, 160, 275, 36);

        Film5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Film5);
        Film5.setBounds(720, 120, 275, 34);

        Film4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Film4);
        Film4.setBounds(720, 80, 275, 34);

        Film6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Film6);
        Film6.setBounds(720, 170, 275, 30);

        Film2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Film2);
        Film2.setBounds(330, 110, 275, 34);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("KATEGORILER");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(630, 690, 195, 37);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(200, 750, 120, 140);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(380, 750, 120, 140);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("BUTUN FILMLER....");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(550, 280, 256, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 250, 1280, 2);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(770, 750, 120, 140);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(1150, 750, 120, 140);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(590, 750, 120, 140);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(970, 750, 120, 140);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 660, 1280, 10);

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(200, 970, 120, 140);

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(380, 970, 120, 140);

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(770, 970, 120, 140);

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(30, 970, 120, 140);

        jButton13.setBackground(new java.awt.Color(0, 0, 0));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(970, 970, 120, 140);

        jButton14.setBackground(new java.awt.Color(0, 0, 0));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(580, 970, 120, 140);

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(1150, 970, 120, 140);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Aksiyon");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 900, 64, 50);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Aksiyon ve Macera");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(200, 910, 130, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Anime");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(400, 920, 80, 14);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Belgesel");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(610, 920, 70, 20);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Bilim Kurgu ve Fantastik");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(750, 920, 170, 17);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Bilim Kurgu ");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(990, 920, 80, 17);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Doga");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(1190, 920, 31, 17);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Drama");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(70, 1150, 50, 17);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Gerilim");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(230, 1150, 60, 17);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Komedi");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(410, 1150, 60, 17);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Korku");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(620, 1150, 40, 17);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Cocuk ve Aile");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(780, 1150, 90, 20);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Reality Show");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(990, 1150, 100, 17);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Romantik");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(1180, 1150, 70, 17);

        arama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aramaKeyReleased(evt);
            }
        });
        jPanel1.add(arama);
        arama.setBounds(20, 290, 260, 30);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Arama Cubugu:");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(50, 1210, 260, 20);

        jButton17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton17.setText("Devam Et");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);
        jButton17.setBounds(940, 480, 150, 25);

        tablo2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProgramAdı", "ProgramTipi", "KacBolum", "BolumUzunluk"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablo2);
        if (tablo2.getColumnModel().getColumnCount() > 0) {
            tablo2.getColumnModel().getColumn(0).setResizable(false);
            tablo2.getColumnModel().getColumn(1).setResizable(false);
            tablo2.getColumnModel().getColumn(2).setResizable(false);
            tablo2.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(450, 1220, 452, 250);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Arama Cubugu:");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(20, 260, 260, 20);

        jButton16.setBackground(new java.awt.Color(0, 0, 0));
        jButton16.setOpaque(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(30, 750, 120, 140);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Puanla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(190, 1390, 90, 30);

        arama2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama2KeyReleased(evt);
            }
        });
        jPanel1.add(arama2);
        arama2.setBounds(50, 1240, 290, 30);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Durdur butonuna basmadan önce aşağıdaki butondan oy veriniz: ");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(20, 1340, 400, 30);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Puan Seçiniz.. ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(40, 530, 119, 40);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("PUANLA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(170, 530, 90, 40);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("HOSGELDINIZZ...");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(10, 10, 160, 30);

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel30);
        jLabel30.setBounds(10, 50, 250, 30);

        jButton19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton19.setText("Durdur");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19);
        jButton19.setBounds(110, 1430, 110, 40);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Kaldığınız filme devam etmek için  ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(940, 390, 370, 30);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("\"Devam Et\" butonuna tıklayabilirsiniz:");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(940, 430, 340, 30);

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Puan Seçiniz...", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(40, 1390, 120, 30);

        jButton21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton21.setText("IZLE ");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21);
        jButton21.setBounds(20, 450, 67, 25);

        jButton20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton20.setText("Durdur");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20);
        jButton20.setBounds(100, 580, 110, 40);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Durdur butonuna basmadan önce aşağıdaki butondan oy veriniz: ");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(20, 500, 400, 30);

        jButton22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton22.setText("İZLE");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton22);
        jButton22.setBounds(50, 1290, 120, 40);

        jButton18.setText("Seçilen Dizinin Bölümlerini Sıralamak İçin Tıklayın");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(20, 340, 420, 40);

        //jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        //jPanel1.add(jLabel2);
        //jLabel2.setBounds(20, 350, 350, 30);

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1517, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void dinamik_ara(String ara){
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<>(model);
        tablo.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    
    private void dinamik_ara2(String ara){
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<>(model2);
        tablo2.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    private void aramaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aramaKeyReleased
        // TODO add your handling code here:
        String ara=arama.getText();
        dinamik_ara(ara);
    }//GEN-LAST:event_aramaKeyReleased

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
      
        int rowIndex = tablo2.getSelectedRow();
        rowIndex = tablo2.convertRowIndexToModel(rowIndex);
        Ad = (String)tablo2.getModel().getValueAt(
                    rowIndex, 0);
        Tip=(String)tablo2.getModel().getValueAt(rowIndex, 1);
        endTime2 = System.currentTimeMillis();
        islem2.izlemeSüreEkle(beginTime2, endTime2);
        if(Tip.equals("Film")){
            String tip="Film";
            int Hangi=1;
        islem2.emailekle(Islemler.getMail(), Islemler.getSüre(), Ad,puan,Hangi,tip);
        }
        if(Tip.equals("Dizi") ){
            String tip="Dizi";
                 
            int Hangi=Integer.parseInt((String) box2.getSelectedItem());
            islem2.emailekle(Islemler.getMail(), Islemler.getSüre(), Ad,puan,Hangi,tip);
        }
        if(Tip.equals("Tv Show") ){
            String tip="Tv Show";
                 
            int Hangi=Integer.parseInt((String) box2.getSelectedItem());
            islem2.emailekle(Islemler.getMail(), Islemler.getSüre(), Ad,puan,Hangi,tip);
        }
       
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        puan =  (String) jComboBox1.getSelectedItem();
        JOptionPane.showMessageDialog(null, "Puanlama basariyla yapildi..... ");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabloMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tabloMouseClicked

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
      Filmleri_goruntule3();  
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       Filmleri_goruntule2();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Filmleri_goruntule4();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        Filmleri_goruntule5();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Filmleri_goruntule6();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Filmleri_goruntule7();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Filmleri_goruntule8();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Filmleri_goruntule9();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Filmleri_goruntule10();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Filmleri_goruntule11();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Filmleri_goruntule12();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Filmleri_goruntule13();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        Filmleri_goruntule14();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        Filmleri_goruntule15();
                
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
      
      //islem2.kaldiginFilmiGoster(KayitOlSayfasi.getEmail2());
      if(islem2.kaldiginFilmiGoster(KayitOlSayfasi.getEmail2()).equals("Film")){
          
      JOptionPane.showMessageDialog(null, Islemler.getProgramAdı()+" filminde "+ Islemler.getIzlemeSure()+" süresinde kaldınız... ");
      }
      if(islem2.kaldiginFilmiGoster(KayitOlSayfasi.getEmail2()).equals("Dizi")){
          
      JOptionPane.showMessageDialog(null, Islemler.getProgramAdı()+" dizisinde "+ Islemler.getBolum()+". bölümde" + Islemler.getIzlemeSure()+" süresinde kaldınız... ");
      }
      if(islem2.kaldiginFilmiGoster(KayitOlSayfasi.getEmail2()).equals("Tv Show")){
      JOptionPane.showMessageDialog(null, Islemler.getProgramAdı()+" Tv Showunda "+ Islemler.getBolum()+". bölümde"+ Islemler.getIzlemeSure()+" süresinde kaldınız... ");
      }
      
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        puan =  (String) jComboBox2.getSelectedItem();
        JOptionPane.showMessageDialog(null, "Puanlama basariyla yapildi..... ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        beginTime = System.currentTimeMillis(); 
        
        JOptionPane.showMessageDialog(null, "İzlemeye basladiniz..", "Mesaj", JOptionPane.YES_OPTION);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
       
        int rowIndex = tablo.getSelectedRow();
        rowIndex = tablo.convertRowIndexToModel(rowIndex);
        Ad = (String)tablo.getModel().getValueAt(
                    rowIndex, 0);
        Tip=(String) tablo.getModel().getValueAt(rowIndex, 1);
        
        endTime = System.currentTimeMillis();
        islem2.izlemeSüreEkle(beginTime, endTime);
        if(Tip.equals("Film")){
            String tip="Film";
            int Hangi=1;
        islem2.emailekle(Islemler.getMail(), Islemler.getSüre(), Ad,puan,Hangi,tip);
        }
        if(Tip.equals("Dizi") ){
            String tip="Dizi";
                 
            int Hangi=Integer.parseInt((String) box2.getSelectedItem());
            islem2.emailekle(Islemler.getMail(), Islemler.getSüre(), Ad,puan,Hangi,tip);
        }
        if(Tip.equals("Tv Show") ){
            String tip="Tv Show";
                 
            int Hangi=Integer.parseInt((String) box2.getSelectedItem());
            islem2.emailekle(Islemler.getMail(), Islemler.getSüre(), Ad,puan,Hangi,tip);
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
               beginTime2 = System.currentTimeMillis(); 
               
               JOptionPane.showMessageDialog(null, "İzlemeye basladiniz.. .");
     
    }//GEN-LAST:event_jButton22ActionPerformed

    private void arama2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama2KeyReleased
        String ara=arama2.getText();
        dinamik_ara2(ara);        
    }//GEN-LAST:event_arama2KeyReleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        int rowIndex = tablo.getSelectedRow();
        rowIndex = tablo.convertRowIndexToModel(rowIndex);
        String Ad2 = (String)tablo.getModel().getValueAt(
                    rowIndex, 0);
       String   Tip2=(String) tablo.getModel().getValueAt(rowIndex, 1);
        
        if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
           if(Ad2.equals("Marvel Iron Fast")){
               
           String [] diziiiii = new String[12];  
            for(int i=0;i<12;i++){
              /// Marvel
              
             diziiiii[i]=""+(i+1);
      
            }
           box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
        if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
            
           if(Ad2.equals("Ejderhalar")){
               
           String [] diziiiii = new String[10];  
            for(int i=0;i<10;i++){
               diziiiii[i]=""+(i+1);       /// Ejderhalar
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
          
           box2.setVisible(true);
           
       }
       }
        if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
           if(Ad2.equals("Diriliş Ertuğrul")){
               
           String [] diziiiii = new String[15];  
            for(int i=0;i<15;i++){
            diziiiii[i]=""+(i+1); /// Diriliş Ertuğrul
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
        if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
           if(Ad2.equals("Troll Avcıları: Arcadia Hikayeleri")){
               
           String [] diziiiii = new String[12];  
            for(int i=0;i<12;i++){
            diziiiii[i]=""+(i+1); /// Trol avcıları
        }
           box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
        if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
           if(Ad2.equals("How I met your mother")){
               
           String [] diziiiii = new String[8];  
            for(int i=0;i<8;i++){
            diziiiii[i]=""+(i+1); /// How I met your
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
        if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
           if(Ad2.equals("Leyla ile Mecnun")){
               
           String [] diziiiii = new String[20];  
            for(int i=0;i<20;i++){
            diziiiii[i]=""+(i+1); /// Leyla ile mecnun
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
         if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
           if(Ad2.equals("Beni Böyle Sev")){
               
           String [] diziiiii = new String[37];  
            for(int i=0;i<37;i++){
            diziiiii[i]=""+(i+1); /// Beni böyle sev
        }
          box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
         if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
           if(Ad2.equals("Patron Bebek Yine İş Başında")){
               
           String [] diziiiii = new String[23];  
            for(int i=0;i<23;i++){
            diziiiii[i]=""+(i+1); /// Patron bebek yine iş başında
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
           if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
           if(Ad2.equals("Atiye")){
               
           String [] diziiiii = new String[24];  
            for(int i=0;i<24;i++){
            diziiiii[i]=""+(i+1); /// Atiye
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
            if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
           if(Ad2.equals("Maşa ve Koca Ayı")){
               
           String [] diziiiii = new String[23];  
            for(int i=0;i<23;i++){
            diziiiii[i]=""+(i+1); /// Maşa ve Koca Ayı
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
            if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
           if(Ad2.equals("Sünger Bob")){
               
           String [] diziiiii = new String[6];  
            for(int i=0;i<6;i++){
            diziiiii[i]=""+(i+1); /// Sünger Bob
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
        
            if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
           if(Ad2.equals("Stranger Things")){
               
           String [] diziiiii = new String[9];  
            for(int i=0;i<9;i++){
            diziiiii[i]=""+(i+1); /// Stranger Things
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
                if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
           if(Ad2.equals("The Originals")){
               
           String [] diziiiii = new String[16];  
            for(int i=0;i<16;i++){
            diziiiii[i]=""+(i+1); /// The Originals
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
        if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
           if(Ad2.equals("Angry Birds")){
               
           String [] diziiiii = new String[9];  
            for(int i=0;i<9;i++){
            diziiiii[i]=""+(i+1); /// Angry Birds
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
        if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
           if(Ad2.equals("Criminal")){
               
           String [] diziiiii = new String[9];  
            for(int i=0;i<9;i++){
            diziiiii[i]=""+(i+1); /// Criminal
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
        if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
           if(Ad2.equals("Beyblade")){
               
           String [] diziiiii = new String[18];  
            for(int i=0;i<18;i++){
            diziiiii[i]=""+(i+1); /// Beyblade
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
        if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
           if(Ad2.equals("Sonic X")){
               
           String [] diziiiii = new String[15];  
            for(int i=0;i<15;i++){
            diziiiii[i]=""+(i+1); /// Sonic X
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
        if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
           if(Ad2.equals("Kung Fu Panda Muhteşem Sırlar")){
               
           String [] diziiiii = new String[27];  
            for(int i=0;i<27;i++){
            diziiiii[i]=""+(i+1); /// Kung Fu Panda Muhteşem Sırlar
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
          if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
           if(Ad2.equals("The Blacklist")){
               
           String [] diziiiii = new String[30];  
            for(int i=0;i<30;i++){
            diziiiii[i]=""+(i+1); /// The Blacklist
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
        if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
           if(Ad2.equals("Dünyanın En Sıradışı Evleri")){
               
           String [] diziiiii = new String[32];  
            for(int i=0;i<32;i++){
            diziiiii[i]=""+(i+1); /// Dünyanın..
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
        if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
 
           if(Ad2.equals("Car Masters")){
               
           String [] diziiiii = new String[15];  
            for(int i=0;i<15;i++){
            diziiiii[i]=""+(i+1); /// Car Masters
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
        if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
    
           if(Ad2.equals("Büyük Tasarımlar")){
               
           String [] diziiiii = new String[22];  
            for(int i=0;i<22;i++){
            diziiiii[i]=""+(i+1); /// Büyük T
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
        if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
      
           if(Ad2.equals("Basketball or Nothing")){
               
           String [] diziiiii = new String[10];  
            for(int i=0;i<10;i++){
            diziiiii[i]=""+(i+1); /// Basketball or Nothing
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
        if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
      
           if(Ad2.equals("The Big Family Cooking")){
           String [] diziiiii = new String[19];  
            for(int i=0;i<19;i++){
            diziiiii[i]=""+(i+1); /// The Big Family Cooking
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           box2.setVisible(true);
           
       }
       }
        if(Tip2.equals("Dizi") || Tip2.equals("Tv Show")){
           if(Ad2.equals("Sıradışı Kulübeler")){
           String [] diziiiii = new String[9];  
            for(int i=0;i<9;i++){
            diziiiii[i]=""+(i+1); ///Sıradışı Kulübeler
        }
            box2=new JComboBox(diziiiii);
           jPanel1.add(box2);
           box2.setBounds(20, 400, 120, 30);
           
           
       }
       }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton18ActionPerformed
 public void Filmleri_goruntule15(){
        model2.setRowCount(0);
         ArrayList <Programlar> filmler3= new ArrayList<Programlar>();
         filmler3= islem2.filmleriGetir15();
         
         if(filmler3 != null){
             for(Programlar programlar2: filmler3){
                 Object[] eklenecek2 = {programlar2.getProgramAdı(), programlar2.getProgramTipi()
          , programlar2.getKacBolum(), programlar2.getZaman()};
                 
                  model2.addRow(eklenecek2);
                 
             }
         }
    }
    public void Filmleri_goruntule14(){
        model2.setRowCount(0);
         ArrayList <Programlar> filmler3= new ArrayList<Programlar>();
         filmler3= islem2.filmleriGetir14();
         
         if(filmler3 != null){
             for(Programlar programlar2: filmler3){
                 Object[] eklenecek2 = {programlar2.getProgramAdı(), programlar2.getProgramTipi()
          , programlar2.getKacBolum(), programlar2.getZaman()};
                 
                  model2.addRow(eklenecek2);
                 
             }
         }
    }
    public void Filmleri_goruntule13(){
        model2.setRowCount(0);
         ArrayList <Programlar> filmler3= new ArrayList<Programlar>();
         filmler3= islem2.filmleriGetir13();
         
         if(filmler3 != null){
             for(Programlar programlar2: filmler3){
                 Object[] eklenecek2 = {programlar2.getProgramAdı(), programlar2.getProgramTipi()
          , programlar2.getKacBolum(), programlar2.getZaman()};
                 
                  model2.addRow(eklenecek2);
                 
             }
         }
    }
    public void Filmleri_goruntule12(){
        model2.setRowCount(0);
         ArrayList <Programlar> filmler3= new ArrayList<Programlar>();
         filmler3= islem2.filmleriGetir12();
         
         if(filmler3 != null){
             for(Programlar programlar2: filmler3){
                 Object[] eklenecek2 = {programlar2.getProgramAdı(), programlar2.getProgramTipi()
          , programlar2.getKacBolum(), programlar2.getZaman()};
                 
                  model2.addRow(eklenecek2);
                 
             }
         }
    }
    public void Filmleri_goruntule11(){
        model2.setRowCount(0);
         ArrayList <Programlar> filmler3= new ArrayList<Programlar>();
         filmler3= islem2.filmleriGetir11();
         
         if(filmler3 != null){
             for(Programlar programlar2: filmler3){
                 Object[] eklenecek2 = {programlar2.getProgramAdı(), programlar2.getProgramTipi()
          , programlar2.getKacBolum(), programlar2.getZaman()};
                 
                  model2.addRow(eklenecek2);
                 
             }
         }
    }
    public void Filmleri_goruntule10(){
        model2.setRowCount(0);
         ArrayList <Programlar> filmler3= new ArrayList<Programlar>();
         filmler3= islem2.filmleriGetir10();
         
         if(filmler3 != null){
             for(Programlar programlar2: filmler3){
                 Object[] eklenecek2 = {programlar2.getProgramAdı(), programlar2.getProgramTipi()
          , programlar2.getKacBolum(), programlar2.getZaman()};
                 
                  model2.addRow(eklenecek2);
                 
             }
         }
    }
    public void Filmleri_goruntule9(){
        model2.setRowCount(0);
         ArrayList <Programlar> filmler3= new ArrayList<Programlar>();
         filmler3= islem2.filmleriGetir9();
         
         if(filmler3 != null){
             for(Programlar programlar2: filmler3){
                 Object[] eklenecek2 = {programlar2.getProgramAdı(), programlar2.getProgramTipi()
          , programlar2.getKacBolum(), programlar2.getZaman()};
                 
                  model2.addRow(eklenecek2);
                 
             }
         }
    }
    public void Filmleri_goruntule8(){
        model2.setRowCount(0);
         ArrayList <Programlar> filmler3= new ArrayList<Programlar>();
         filmler3= islem2.filmleriGetir8();
         
         if(filmler3 != null){
             for(Programlar programlar2: filmler3){
                 Object[] eklenecek2 = {programlar2.getProgramAdı(), programlar2.getProgramTipi()
          , programlar2.getKacBolum(), programlar2.getZaman()};
                 
                  model2.addRow(eklenecek2);
                 
             }
         }
    }
    public void Filmleri_goruntule7(){
        model2.setRowCount(0);
         ArrayList <Programlar> filmler3= new ArrayList<Programlar>();
         filmler3= islem2.filmleriGetir7();
         
         if(filmler3 != null){
             for(Programlar programlar2: filmler3){
                 Object[] eklenecek2 = {programlar2.getProgramAdı(), programlar2.getProgramTipi()
          , programlar2.getKacBolum(), programlar2.getZaman()};
                 
                  model2.addRow(eklenecek2);
                 
             }
         }
    }
    public void Filmleri_goruntule6(){
        model2.setRowCount(0);
         ArrayList <Programlar> filmler3= new ArrayList<Programlar>();
         filmler3= islem2.filmleriGetir6();
         
         if(filmler3 != null){
             for(Programlar programlar2: filmler3){
                 Object[] eklenecek2 = {programlar2.getProgramAdı(), programlar2.getProgramTipi()
          , programlar2.getKacBolum(), programlar2.getZaman()};
                 
                  model2.addRow(eklenecek2);
                 
             }
         }
    }
    public void Filmleri_goruntule5(){
        model2.setRowCount(0);
         ArrayList <Programlar> filmler3= new ArrayList<Programlar>();
         filmler3= islem2.filmleriGetir5();
         
         if(filmler3 != null){
             for(Programlar programlar2: filmler3){
                 Object[] eklenecek2 = {programlar2.getProgramAdı(), programlar2.getProgramTipi()
          , programlar2.getKacBolum(), programlar2.getZaman()};
                 
                  model2.addRow(eklenecek2);
                 
             }
         }
    }
    public void Filmleri_goruntule4(){
        model2.setRowCount(0);
         ArrayList <Programlar> filmler3= new ArrayList<Programlar>();
         filmler3= islem2.filmleriGetir4();
         
         if(filmler3 != null){
             for(Programlar programlar2: filmler3){
                 Object[] eklenecek2 = {programlar2.getProgramAdı(), programlar2.getProgramTipi()
          , programlar2.getKacBolum(), programlar2.getZaman()};
                 
                  model2.addRow(eklenecek2);
                 
             }
         }
    }
    public void Filmleri_goruntule3(){
        model2.setRowCount(0);
         ArrayList <Programlar> filmler3= new ArrayList<Programlar>();
         filmler3= islem2.filmleriGetir3();
         
         if(filmler3 != null){
             for(Programlar programlar2: filmler3){
                 Object[] eklenecek2 = {programlar2.getProgramAdı(), programlar2.getProgramTipi()
          , programlar2.getKacBolum(), programlar2.getZaman()};
                 
                  model2.addRow(eklenecek2);
                 
             }
         }
    }
     public void Filmleri_goruntule2(){
         
         model2.setRowCount(0);
         ArrayList <Programlar> filmler2= new ArrayList<Programlar>();
         filmler2= islem2.filmleriGetir2();
         
         if(filmler2 != null){
             for(Programlar programlar2: filmler2){
                 Object[] eklenecek2 = {programlar2.getProgramAdı(), programlar2.getProgramTipi()
          , programlar2.getKacBolum(), programlar2.getZaman()};
                 
                  model2.addRow(eklenecek2);
                 
             }
         }
     }
     public void Filmleri_goruntule(){
        model.setRowCount(0);
        ArrayList<Programlar> filmler = new ArrayList<Programlar>();
        filmler = islem2.filmleriGetir();
        
        if(filmler != null){
            for(Programlar programlar : filmler){
                Object[] eklenecek = {programlar.getProgramAdı(), programlar.getProgramTipi()
          , programlar.getKacBolum(), programlar.getZaman()};
                
                model.addRow(eklenecek);
            }
            }
        }
     
     
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialog1 dialog = new NewJDialog1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Film1;
    private javax.swing.JLabel Film2;
    private javax.swing.JLabel Film3;
    private javax.swing.JLabel Film4;
    private javax.swing.JLabel Film5;
    private javax.swing.JLabel Film6;
    private javax.swing.JTextField arama;
    private javax.swing.JTextField arama2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    //private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tablo;
    private javax.swing.JTable tablo2;
    // End of variables declaration//GEN-END:variables
}
